Feature/omb 1 testing
GSA/eoc pull request #501
Opened 2024-06-20 15:46 UTC by KevinWilsonOMB

This is basically the same as the previous Pull Request which I closed, the only difference is the prefix path which I believe I have now set correctly.

2024-06-25 13:59 UTC, istankevychgsa commented
Here is a demo link: https://federalist-a1f29504-db06-4d32-992e-c2dadbfe82f2.sites.pages.cloud.gov/preview/gsa/eoc/feature/OMB-1-Testing/projects/Feature_EvidencePortal_InitialCheckIn/evidence-portal/

Change your prefix path to /projects and copy your files from Feature_EvidencePortal_InitialCheckIn/evidence-portal/ directly into the /projects directory.

2024-06-25 14:42 UTC, istankevychgsa requested changes
Please use /project folder

2024-06-25 14:42 UTC, istankevychgsa commented on _pages/evidence-portal/2edb282b-cb5f72dd98e78832e65e.js
Please use the /projects folder instead.

2024-08-16 13:04 UTC, istankevychgsa requested changes

2024-08-16 13:04 UTC, istankevychgsa commented on .gitignore
> +
revert all changes for this file. Use .gitignore file from the **main** branch

2024-08-16 18:27 UTC, KevinWilsonOMB commented
Package jsons were accidently checked in, too much to resolve and will create a new PR.

2024-08-16 18:27 UTC, closed without merging